### ISSUE TITLE
The mobile menu should close after you click on a link

### ISSUE THREAD

**Issue by ambergkim** [nourimeals/website#111]
Currently, if people want to navigate to the About section or to another section, on mobile.

What happens:
- People click on the hamburger to open the mobile menu
- They click on the link they want to go to
- The website BEHIND the menu, scrolls to the correct place
- The menu stays open so the user will have to close the menu before they can go to read what they need to know

The Biggest Issue:
- It might not even look to the user that they have navigated to the correct spot

Solution:
- Have the menu close after a click.

**Comment by gabrielatricak** [comment]
hi i would like to work on this. Can i be assigned to this?

**Comment by RaevLogic** [comment]
It's all yours. Just let us know if you have questions or need any help.
