### ISSUE TITLE
Page images browser compatibility

### ISSUE THREAD

**Issue by ambergkim** [nourimeals/website#112]
The hero image displays differently between browsers in larger (desktop) screens.

The image appears correctly in Chrome and Firefox but in Safari, it does not. See screenshot:
<img width="1440" alt="Screen Shot 2020-10-04 at 12 06 40 PM" src="https://user-images.githubusercontent.com/14047327/95024818-5fcbe580-063a-11eb-8548-6bd8da1a4686.png">

The next image below is also having the same issue

<img width="546" alt="Screen Shot 2020-10-04 at 12 12 28 PM" src="https://user-images.githubusercontent.com/14047327/95024934-f39db180-063a-11eb-9449-df15d3bf1c84.png">

**Comment by viki-korotkaya** [comment]
I have taken this bug. Is it ok?

**Comment by RaevLogic** [comment]
Sure, have at it.
