### ISSUE TITLE
Add a border or shadow to the PopUp component

### ISSUE THREAD

**Issue by RaevLogic** [nourimeals/website#126]
**Describe the bug**
PopUp component needs a border or shadow added so a user can clearly tell where the box is.

**To Reproduce**
1. Go to nourimeals.com
2. Click on the 'connect with email' button
3. ???
4. See error (and profit)

**Expected behavior**
PopUp should have some sort of border or shadow to make it "pop" from the website.

**Screenshots**
With no popup.
![image](https://user-images.githubusercontent.com/38801291/96743091-3d9bcc80-1389-11eb-86be-3eb0ee57c7ca.png)

With popup.
![image](https://user-images.githubusercontent.com/38801291/96743144-4b515200-1389-11eb-847c-f2aab77bf338.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: new

**Comment by rhtaylor** [comment]
I'll take this and get it done this pm.
