### ISSUE TITLE
Add link to blog

### ISSUE THREAD

**Issue by ambergkim** [nourimeals/website#48]

**Comment by ambergkim** [comment]
- [ ] Start with adding blog to the dropdown menu: https://medium.com/@nourimeals
- [ ] Stretch goal, adding the menu to the footer.

**Comment by RaevLogic** [comment]
I see the blog hasn't been updated in some time. Is this still something you'd like to pursue Amber?

**Comment by ambergkim** [comment]
@RaevLogic It would be good. If you want to add posts or topics, let me know

**Comment by ColeMiller21** [comment]
This was accomplished in the social media links issue that was just resolved

**Comment by RaevLogic** [comment]
Noted.
