### ISSUE TITLE
Add links to social media pages

### ISSUE THREAD

**Issue by ambergkim** [nourimeals/website#49]
- [ ] Facebook https://www.facebook.com/teamnouri/
- [ ] LinkedIN https://linkedin.com/company/teamnouri
- [ ] Twitter https://twitter.com/TeamNouri
- [ ] Medium https://medium.com/@teamnouri

Add to footer.

**Comment by RaevLogic** [comment]
I'm going to close out the related PR as we're waiting for the new overhaul PR to come through. However, I'm going to post the comments from the original PR here so they're not forgotten.

- Can we make the icons bigger especially on mobile so it's easier for a big finger to click one?

- When making changes to front end stuff, it's best to add before and after screenshots.

- Read up on tags and how to optimize them for accessibility and SEO.

**Comment by RaevLogic** [comment]
From Kyle H:

- In terms of accessibility, you're rendering these links with SVGs as their "content". For somebody that can't see the symbols - they'll have no context of what they're being linked to. FontAwesome icons don't use a title element to provide context about their icon so it's up to you to provide text that a screen reader would parse.

I recommend creating a ScreenReaderOnly component that has invisible, but rendered text. Your seeing-eye users will see the icons, and your screen reader-using users will be given the proper context. A good example would be:

<a href="https://linkedin.com/company/teamnouri">
  <ScreenReaderOnly>teamnouri on LinkedIn</ScreenReaderOnly>
  {linkedinSocial}
</a>
This methodology will also help you earn points with SEO audits for having descriptive text in hyperlinks.

See: https://github.com/OperationCode/front-end/tree/master/components/ScreenReaderOnly
