### ISSUE TITLE
Add Address

### ISSUE THREAD

**Issue by ambergkim** [nourimeals/website#55]

**Comment by RaevLogic** [comment]
This is super vague. Do you want the nonprofit's actual physical address somewhere on the page? Mailing address?

**Comment by ambergkim** [comment]
We have this address. We can add it to the page.
7241 185th Ave. NE #3472
Redmond, WA

**Comment by RaevLogic** [comment]
- [ ] Completed

We can add this to the footer at some point as we refine it.

**Comment by rhtaylor** [comment]
How would you like this added/implemented? plain text to the string? I could go the React way and make a component that housed all this information. Something to consider further down is to implement a master-detail pattern of nested routing with an "Address" link to display the component for the address and even a info link to display a component for the info. That may be more effort that necessary for a "footer" of basic info/address.

**Comment by RaevLogic** [comment]
![image](https://user-images.githubusercontent.com/38801291/89227732-d188a400-d5a3-11ea-8feb-2f1e115f2f23.png)

So here's a pic of our footer at the moment. I would say we can just keep it simple and have the address just be text for now. 

- Option 1 would be to center the Nouri non-profit statement, and then put the address directly below it. You could have the address inside its own little div so you can center it nicely. 

-Option 2 would be to put both the non-profit statement AND the address in their own separate divs, and have them side by side inside the footer.

**Comment by ambergkim** [comment]
This has already been added and is live.
