### ISSUE TITLE
Add gray or border and/or background to popup

### ISSUE THREAD

**Issue by ambergkim** [nourimeals/website#57]
The mailing list signup pop up has a white background and the page also has a white background. When they overlap, the popup doesn’t stand apart from the page.

Add a border, possibly a different color background (very light gray) and possibly a drop shadow around the popup.

![440CEF0E-4A6F-4E5D-B31D-5B0A49D8A20C](https://user-images.githubusercontent.com/14047327/62829484-6df7b080-bbb3-11e9-8d14-312135a3efc4.png)

**Comment by RaevLogic** [comment]
This isn't completed yet. Waiting to see incoming PR from EB.

**Comment by RaevLogic** [comment]
Update: this actually is in place when I click the 'Get Updates' button on desktop, even at mobile screen size. However, it does not happen on my actual phone.

**Comment by RaevLogic** [comment]
Closing now, Website overhaul completed.
