### ISSUE TITLE
Refine about page/section responsiveness.

### ISSUE THREAD

**Issue by ambergkim** [nourimeals/website#58]
We only have two break points so some screen sizes are not accomodated.

**Comment by RaevLogic** [comment]
Still an open issue

**Comment by RaevLogic** [comment]
Research 'mobile-first' design philosophy and make sure we are following correctly. The website currently seems to have different breakpoints depending on which `.scss` file you're in.

**Comment by rhtaylor** [comment]
Looking at the top results from a google search 'mobile-first design pattern' I get this: "design for the smallest screen possible" then when the screen size increases to the point where the layout loses aesthetic create a breakpoint. I only have two screens I can test on; My android moto z3 at 1080x2160 pixels and my asus notebook at 1920 x 1080 pixels. 

Using this philosophy I do not know where an appropriate size to create a breakpoint would be.

**Comment by ambergkim** [comment]
Not all breakpoints need to be supported. Check in Google Crome dev tools. It will have the preview for different screen sizes. You can use what they have as a guide. If something looks weird in that screen size, fix it and add a new breakpoint if necessary. Be minimalistic so there is less stuff to manage.

Don't forget landscape bs portrait sizes.

**Comment by rhtaylor** [comment]
👍 Chrome saves the day. Ideally We should act as if every user has the smallest screen possible. Then if the screen the page is loading on is bigger add more to it. Is the current content what you would like to keep no matter the size? two questions: 
1) Is there anything that could/should be removed? Currently there is a lot of scrolling on smaller screens with no loss of functionality. 
2) Is there anything specific UI issue I should be aware of when the screen size changes?

**Comment by ambergkim** [comment]
The mockups have some things disappear like the board member images so there is less scrolling. It's ok to not display unnecessary items on mobile.

Keep in mind that on. I ole devices, things like buttons tend to be bigger to accommodate fingers. On desktop, it's not as important as people usually have mouse pointers.

Another thing to think about is how things will display above the fold. One of the things we should be able to show easily without scrolling is the main call to action.

**Comment by RaevLogic** [comment]
Bootstrap has common breakpoints listed that you can use that should be perfectly fine for our needs.

https://getbootstrap.com/docs/4.5/layout/overview/

**Comment by RaevLogic** [comment]
reference PR #91
