### ISSUE TITLE
Recreate into a simple landing page

### ISSUE THREAD

**Issue by ambergkim** [nourimeals/website#59]
Landing page should include:

A summary of Nouri
Sign up to Get Updates
Sign up to Volunteer

- [ ] Create wireframe

- [ ] Detail a layout

- [ ] Create tests

- [ ] Create summary section

- [ ] Create volunteer section

**Comment by ambergkim** [comment]
@bokoblin-link 
An idea:

H1: Leveraging technologies to eliminate childhood hunger
H2: Get involved and stay up to date
BIG BUTTON: Subscribe
Small Link: Volunteer

**Comment by RaevLogic** [comment]
This issue has technically been completed. Not sure if you want to update it or just close it and work on individual issues once EB submits her PR.

**Comment by ambergkim** [comment]
@RaevLogic We can just close this.
