### ISSUE TITLE
Link to Nouri Resources: Webinar Documents

### ISSUE THREAD

**Issue by ambergkim** [nourimeals/website#88]
- https://github.com/nourimeals/documents/tree/master/Webinars

**Comment by ambergkim** [comment]
Menu is good

**Comment by rhtaylor** [comment]
What should the text say for this link? resources? Should the link be copied literally or should I pick something more specific such as the directory that leads to https://github.com/nourimeals/documents/tree/master/Webinars/Small%20Business%20Resources 
What order would you like the links? Alphabetical? Insert this First? Insert this Last?

**Comment by RaevLogic** [comment]
- "Resources" is fine.
- Copied literally. We will probably add other resources in the future aside from the Small Business ones.
- You can just put this in last. So it should be on the bottom when you open the hamburger menu, and closest to the donate button in the navbar.

**Comment by rhtaylor** [comment]
To be clear. I have added a link to our github pages directory for resources with the link text reading Resources exactly. I will have Roger review the pull request.

**Comment by RaevLogic** [comment]
Reference #99
